import 'package:cloud_firestore/cloud_firestore.dart';

class ReceiptEntity {
  final int imei;
  final int receiptNo;
  final String customerName;
  final String customerPhoneNo;
  final String deviceDatails;
  final int cashPrice;
  final List<String> receiptImgUrl;
  final String shopId;
  final DateTime receiptDate;
  final DateTime addeOn;
  final String smUuid;
  final String org;

  ReceiptEntity({
    required this.imei,
    required this.receiptNo,
    required this.customerName,
    required this.customerPhoneNo,
    required this.deviceDatails,
    required this.cashPrice,
    required this.receiptImgUrl,
    required this.shopId,
    required this.receiptDate,
    required this.addeOn,
    required this.smUuid,
    required this.org,
  });

  // getters
  String get getReceiptNo => '#$receiptNo';

  static ReceiptEntity get empty => ReceiptEntity(
        imei: 0,
        receiptNo: 0,
        customerName: '',
        customerPhoneNo: '',
        deviceDatails: '',
        cashPrice: 0,
        receiptImgUrl: [],
        shopId: '',
        receiptDate: DateTime.now(),
        addeOn: DateTime.now(),
        smUuid: '',
        org: '',
      );

  ReceiptEntity.fromQuerySnapshot(
      {required QueryDocumentSnapshot<Map<String, dynamic>> documentSnapshot})
      : imei = documentSnapshot['imei'],
        receiptNo = documentSnapshot['receiptNo'],
        customerName = documentSnapshot['customerName'],
        customerPhoneNo = documentSnapshot['customerPhoneNo'],
        deviceDatails = documentSnapshot['deviceDatails'],
        cashPrice = documentSnapshot['cashPrice'],
        receiptImgUrl = documentSnapshot['receiptImgUrl'].cast<String>(),
        shopId = documentSnapshot['shopId'],
        receiptDate = DateTime.parse(documentSnapshot['receiptDate']),
        addeOn = DateTime.parse(documentSnapshot['addeOn']),
        smUuid = documentSnapshot['smUuid'],
        org = documentSnapshot['org'];

    ReceiptEntity.fromDocSnapshot(
      {required DocumentSnapshot<Map<String, dynamic>> documentSnapshot})
      : imei = documentSnapshot['imei'],
        receiptNo = documentSnapshot['receiptNo'],
        customerName = documentSnapshot['customerName'],
        customerPhoneNo = documentSnapshot['customerPhoneNo'],
        deviceDatails = documentSnapshot['deviceDatails'],
        cashPrice = documentSnapshot['cashPrice'],
        receiptImgUrl = documentSnapshot['receiptImgUrl'].cast<String>(),
        shopId = documentSnapshot['shopId'],
        receiptDate = DateTime.parse(documentSnapshot['receiptDate']),
        addeOn = DateTime.parse(documentSnapshot['addeOn']),
        smUuid = documentSnapshot['smUuid'],
        org = documentSnapshot['org'];

  Map<String, dynamic> toJson() => {
        'imei': imei,
        'receiptNo': receiptNo,
        'customerName': customerName,
        'customerPhoneNo': customerPhoneNo,
        'deviceDatails': deviceDatails,
        'cashPrice': cashPrice,
        'receiptImgUrl': receiptImgUrl,
        'shopId': shopId,
        'receiptDate': receiptDate.toIso8601String(),
        'addeOn': addeOn.toIso8601String(),
        'smUuid': smUuid,
        'org': org,
      };

  //  copywith method
  ReceiptEntity copyWith({
    int? imei,
    int? receiptNo,
    String? customerName,
    String? customerPhoneNo,
    String? deviceDatails,
    int? cashPrice,
    List<String>? receiptImgUrl,
    String? shopId,
    DateTime? receiptDate,
    DateTime? addeOn,
    String? smUuid,
    String? org,
  }) {
    return ReceiptEntity(
      imei: imei ?? this.imei,
      receiptNo: receiptNo ?? this.receiptNo,
      customerName: customerName ?? this.customerName,
      customerPhoneNo: customerPhoneNo ?? this.customerPhoneNo,
      deviceDatails: deviceDatails ?? this.deviceDatails,
      cashPrice: cashPrice ?? this.cashPrice,
      receiptImgUrl: receiptImgUrl ?? this.receiptImgUrl,
      shopId: shopId ?? this.shopId,
      receiptDate: receiptDate ?? this.receiptDate,
      addeOn: addeOn ?? this.addeOn,
      smUuid: smUuid ?? this.smUuid,
      org: org ?? this.org,
    );
  }
}

List<ReceiptEntity> rs = [
  ReceiptEntity(
    imei: 350988958218903,
    receiptNo: 6786,
    customerName: 'ROSE NYAWIRA MWANGI',
    customerPhoneNo: '0712345678',
    deviceDatails: 'A05(4+64)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 're6786',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now(),
    smUuid: 'sm6786',
    org: 'watu',
  ),
  ReceiptEntity(
    imei: 350280673874883,
    receiptNo: 6787,
    customerName: 'JANE GACHERI MUKIRA',
    customerPhoneNo: '0712345678',
    deviceDatails: 'P55(4+128)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'rd6787',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now(),
    smUuid: 'sm6787',
    org: 'mkopa',
  ),
  ReceiptEntity(
    imei: 350988958218887,
    receiptNo: 6788,
    customerName: 'CAROLYNE IJAI',
    customerPhoneNo: '0712345678',
    deviceDatails: 'A70(6+128)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'zs6788',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 1)),
    smUuid: 'sm6788',
    org: 'onfon',
  ),
  ReceiptEntity(
    imei: 358520503474137,
    receiptNo: 6789,
    customerName: 'FRANKLIN WEKESA',
    customerPhoneNo: '0712345678',
    deviceDatails: 'POP 8(3+64)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'mk6789',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 1)),
    smUuid: 'sm6789',
    org: 'other',
  ),
  ReceiptEntity(
    imei: 350988958218903,
    receiptNo: 6786,
    customerName: 'ROSE NYAWIRA MWANGI',
    customerPhoneNo: '0712345678',
    deviceDatails: 'A05(4+64)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 're6786',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 1)),
    smUuid: 'sm6786',
    org: 'watu',
  ),
  ReceiptEntity(
    imei: 350280673874883,
    receiptNo: 6787,
    customerName: 'JANE GACHERI MUKIRA',
    customerPhoneNo: '0712345678',
    deviceDatails: 'P55(4+128)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'rd6787',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 2)),
    smUuid: 'sm6787',
    org: 'watu',
  ),
  ReceiptEntity(
    imei: 350988958218887,
    receiptNo: 6788,
    customerName: 'CAROLYNE IJAI',
    customerPhoneNo: '0712345678',
    deviceDatails: 'A70(6+128)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'zs6788',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 2)),
    smUuid: 'sm6788',
    org: 'watu',
  ),
  ReceiptEntity(
    imei: 358520503474137,
    receiptNo: 6789,
    customerName: 'FRANKLIN WEKESA',
    customerPhoneNo: '0712345678',
    deviceDatails: 'POP 8(3+64)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'mk6789',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 3)),
    smUuid: 'sm6789',
    org: 'mkopa',
  ),
  ReceiptEntity(
    imei: 350988958218903,
    receiptNo: 6786,
    customerName: 'ROSE NYAWIRA MWANGI',
    customerPhoneNo: '0712345678',
    deviceDatails: 'A05(4+64)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 're6786',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 3)),
    smUuid: 'sm6786',
    org: 'watu',
  ),
  ReceiptEntity(
    imei: 350280673874883,
    receiptNo: 6787,
    customerName: 'JANE GACHERI MUKIRA',
    customerPhoneNo: '0712345678',
    deviceDatails: 'P55(4+128)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'rd6787',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 3)),
    smUuid: 'sm6787',
    org: 'onfon',
  ),
  ReceiptEntity(
    imei: 350988958218887,
    receiptNo: 6788,
    customerName: 'CAROLYNE IJAI',
    customerPhoneNo: '0712345678',
    deviceDatails: 'A70(6+128)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'zs6788',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 3)),
    smUuid: 'sm6788',
    org: 'onfon',
  ),
  ReceiptEntity(
    imei: 358520503474137,
    receiptNo: 6789,
    customerName: 'FRANKLIN WEKESA',
    customerPhoneNo: '0712345678',
    deviceDatails: 'POP 8(3+64)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'mk6789',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 3)),
    smUuid: 'sm6789',
    org: 'mkopa',
  ),
  ReceiptEntity(
    imei: 350988958218903,
    receiptNo: 6786,
    customerName: 'ROSE NYAWIRA MWANGI',
    customerPhoneNo: '0712345678',
    deviceDatails: 'A05(4+64)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 're6786',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 5)),
    smUuid: 'sm6786',
    org: 'watu',
  ),
  ReceiptEntity(
    imei: 350280673874883,
    receiptNo: 6787,
    customerName: 'JANE GACHERI MUKIRA',
    customerPhoneNo: '0712345678',
    deviceDatails: 'P55(4+128)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'rd6787',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now(),
    smUuid: 'sm6787',
    org: 'watu',
  ),
  ReceiptEntity(
    imei: 350988958218887,
    receiptNo: 6788,
    customerName: 'CAROLYNE IJAI',
    customerPhoneNo: '0712345678',
    deviceDatails: 'A70(6+128)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'zs6788',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 6)),
    smUuid: 'sm6788',
    org: 'watu',
  ),
  ReceiptEntity(
    imei: 358520503474137,
    receiptNo: 6789,
    customerName: 'FRANKLIN WEKESA',
    customerPhoneNo: '0712345678',
    deviceDatails: 'POP 8(3+64)',
    cashPrice: 100000,
    receiptImgUrl: ['https://via.placeholder.com/150'],
    shopId: 'mk6789',
    receiptDate: DateTime.now(),
    addeOn: DateTime.now().subtract(const Duration(days: 6)),
    smUuid: 'sm6789',
    org: 'mkopa',
  ),
];
