name: kaisa
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # authentication
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  google_sign_in: ^6.2.1

  # database and files
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

  # state management & routing
  go_router: ^14.2.3
  get: ^4.6.6
  dartz: ^0.10.1
  intl: ^0.19.0
  email_validator: ^3.0.0
  flutter_svg: ^2.0.10+1
  loading_animation_widget: ^1.2.1
  cloud_firestore: ^5.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  uuid: ^4.4.2
  internet_connection_checker: ^2.0.0
  ai_barcode_scanner: ^5.1.1+2
  cached_network_image: ^3.4.0
  dio: ^5.7.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner:
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.4.0

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#2A3042"
  image: assets/images/splash.png
  android: true
  ios: false
  web: false
  android_12:
    # light mode
    color: "#FFFFFF"
    image: assets/images/splash-android-12.png
    icon_background_color: "#FFFFFF"
    # dark mode
    color_dark: "#2A3042"
    image_dark: assets/images/splash-android-12.png
    icon_background_color_dark: "#2A3042"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
